### ISSUE TITLE
dependancy issue for awssum and awssum-amazon

### ISSUE THREAD

**Issue by kanle485** [chilts/awssum-amazon-ses#1]
when i add "awssum-amazon-ses" to my package.json and make npm install, it does not automatically install awssum and awssum-amazon , even though the docs say you don't need to add them explicitly

**Comment by chilts** [comment]
You have an older version of npm which doesn't install peerDependencies.

I'm experimenting with adding those packages as both dependencies and peerDependencies to see if both newer and older versions of npm still do the right thing.

Cheers,
Andy

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
