### ISSUE TITLE
there is no documentation

### ISSUE THREAD

**Issue by kanle485** [chilts/awssum-amazon-ses#2]
I have no idea how to use this plugin, there is absolutely no documentation.
Even 1 small example should be provided.

**Comment by chilts** [comment]
Absolutely. It's on my ToDo list (along with the other 25 plugins). :) You should be able to get some idea on how to use it by browsing something like https://github.com/awssum/awssum-amazon-s3/ and just substituting which operations you need.

Cheers,
Andy

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
